# Generated by Django 5.1.1 on 2024-10-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
